// Generated by gencpp from file opencv_application/kinect.msg
// DO NOT EDIT!


#ifndef OPENCV_APPLICATION_MESSAGE_KINECT_H
#define OPENCV_APPLICATION_MESSAGE_KINECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace opencv_application
{
template <class ContainerAllocator>
struct kinect_
{
  typedef kinect_<ContainerAllocator> Type;

  kinect_()
    : x(0)
    , y(0)
    , name()  {
    }
  kinect_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::opencv_application::kinect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opencv_application::kinect_<ContainerAllocator> const> ConstPtr;

}; // struct kinect_

typedef ::opencv_application::kinect_<std::allocator<void> > kinect;

typedef boost::shared_ptr< ::opencv_application::kinect > kinectPtr;
typedef boost::shared_ptr< ::opencv_application::kinect const> kinectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opencv_application::kinect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opencv_application::kinect_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::opencv_application::kinect_<ContainerAllocator1> & lhs, const ::opencv_application::kinect_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::opencv_application::kinect_<ContainerAllocator1> & lhs, const ::opencv_application::kinect_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace opencv_application

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::opencv_application::kinect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opencv_application::kinect_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opencv_application::kinect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opencv_application::kinect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencv_application::kinect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencv_application::kinect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opencv_application::kinect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "328a8762c487b00a719cc4b35acd34d1";
  }

  static const char* value(const ::opencv_application::kinect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x328a8762c487b00aULL;
  static const uint64_t static_value2 = 0x719cc4b35acd34d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::opencv_application::kinect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opencv_application/kinect";
  }

  static const char* value(const ::opencv_application::kinect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opencv_application::kinect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y\n"
"string name\n"
;
  }

  static const char* value(const ::opencv_application::kinect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opencv_application::kinect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kinect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opencv_application::kinect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opencv_application::kinect_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENCV_APPLICATION_MESSAGE_KINECT_H
